version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
